version: '3'

services:
  #   vehiculumapp:
  #     depends_on:
  #       - db
  #     build:
  #       context: .
  #       dockerfile: Dockerfile
  #     image: vehiculum-docker
  #     container_name: vehiculumapp
  #     restart: always # reiniciar el contenedor si se detiene
  #     ports:
  #       - '${PORT}:${PORT}'
  #     # working_dir: /var/www/vehiculum
  #     environment:
  #       MONGODB: ${MONGODB}
  #       PORT: ${PORT}
  #       DEFAULT_LIMIT: ${DEFAULT_LIMIT}
  #     # volumes:
  #     #   - ./:/var/www/vehiculum

  db:
    image: mongo:5
    container_name: mongo-vehiculum
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: nest-vehiculum
    volumes:
      - ./mongo:/data/db
